image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install development dependencies
    init: |
      julia --project=. -e 'using Pkg; Pkg.instantiate()' &&
      julia dev/install_julia_dependencies.jl &&
      pip install -v -r dev/requirements.txt &&
      gp sync-done dev_dependencies
  - name: Run JupyterLab
    init: gp sync-await dev_dependencies
    command: |
      jupyter lab --no-browser --ip=0.0.0.0 --port=9999 --NotebookApp.token='' --NotebookApp.password=''

ports:
  - name: JupyterLab
    port: 9999
    onOpen: notify

vscode:
  extensions:
    - julialang.language-julia
    - singularitti.vscode-julia-formatter
    
