image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install development dependencies
    init: |
      mkdir -p julia
      wget https://julialang-s3.julialang.org/bin/linux/x64/1.8/julia-1.8.5-linux-x86_64.tar.gz -O julia/julia-1.8.5-linux-x86_64.tar.gz
      tar xvzf julia/julia-1.8.5-linux-x86_64.tar.gz --directory julia/
      export PATH=/workspace/rethinking-2ed-julia/julia/julia-1.8.5/bin/:$PATH
      julia/julia-1.8.5/bin/julia --project=. -e 'using Pkg; Pkg.instantiate()' &&
      julia/julia-1.8.5/bin/julia dev/install_julia_dependencies.jl &&
      pip install -v -r dev/requirements.txt &&
      gp sync-done dev_dependencies
  - name: Run JupyterLab
    init: gp sync-await dev_dependencies
    command: |
      jupyter lab --no-browser --ip=0.0.0.0 --port=9999 --NotebookApp.token='' --NotebookApp.password=''

ports:
  - name: JupyterLab
    port: 9999
    onOpen: notify

vscode:
  extensions:
    - julialang.language-julia
    - singularitti.vscode-julia-formatter
    
